from __future__ import annotations

from pathlib import Path
from typing import Dict

from .models import DEFAULT_PROPERTIES


def read_properties(path: Path) -> Dict[str, str]:
    values = dict(DEFAULT_PROPERTIES)
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    values["server-ip"] = values.get("server-ip", "")
    return values


def write_properties(path: Path, values: Dict[str, str]) -> None:
    merged = dict(DEFAULT_PROPERTIES)
    merged.update(values)
    merged["server-ip"] = ""
    lines = ["# Generated by Gestion Serveurs Minecraft"]
    for key in DEFAULT_PROPERTIES:
        lines.append(f"{key}={merged.get(key, '')}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
